name: Latest Blog Posts
on:
  schedule:
    - cron: '0 0 11 1/1 * ? *' 
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Updated readme"
          feed_list: 'https://bsssss.tistory.com/rss'
          max_post_count: '3'
